(() => { const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  $('#year').textContent=new Date().getFullYear();
  const menu=$('.menu-btn'), side=$('.sidebar'); menu.addEventListener('click',()=>{const open=side.classList.toggle('open');menu.setAttribute('aria-expanded',open);}); $$('nav a').forEach(a=>a.addEventListener('click',()=>side.classList.remove('open')));
  const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches; const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.14});$$('.reveal').forEach(e=>observer.observe(e));
  const navLinks=$$('nav a'), sections=$$('main section[id]'); const navObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}}),{rootMargin:'-35% 0px -55%'});sections.forEach(s=>navObserver.observe(s));
  const glow=$('.cursor-glow'); if(!reduce&&innerWidth>760) addEventListener('pointermove',e=>{glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'; const stage=$('#portraitStage'); if(stage){const r=stage.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)/r.width,y=(e.clientY-r.top-r.height/2)/r.height;stage.style.transform=`translate(${x*7}px,${y*7}px)`}});
  $$('.magnetic').forEach(b=>b.addEventListener('pointermove',e=>{if(reduce)return;const r=b.getBoundingClientRect();b.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.12}px,${(e.clientY-r.top-r.height/2)*.12}px)`}));$$('.magnetic').forEach(b=>b.addEventListener('pointerleave',()=>b.style.transform=''));
  const canvas=$('#universe'); if(canvas&&!reduce&&innerWidth>600){const c=canvas.getContext('2d');let pts=[],w,h,mouse={x:0,y:0};function resize(){w=canvas.width=canvas.clientWidth*devicePixelRatio;h=canvas.height=canvas.clientHeight*devicePixelRatio;c.scale(devicePixelRatio,devicePixelRatio);w=canvas.clientWidth;h=canvas.clientHeight;pts=Array.from({length:innerWidth<900?28:54},()=>({x:Math.random()*w,y:Math.random()*h,vx:(Math.random()-.5)*.22,vy:(Math.random()-.5)*.22,r:Math.random()*1.2+.3}))}addEventListener('resize',resize);addEventListener('pointermove',e=>mouse={x:e.clientX,y:e.clientY});function draw(){c.clearRect(0,0,w,h);for(const p of pts){p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>w)p.vx*=-1;if(p.y<0||p.y>h)p.vy*=-1;const d=Math.hypot(p.x-mouse.x,p.y-mouse.y);if(d<130){p.x+=(p.x-mouse.x)/d*.35;p.y+=(p.y-mouse.y)/d*.35}c.fillStyle='rgba(213,255,64,.7)';c.beginPath();c.arc(p.x,p.y,p.r,0,7);c.fill();for(const q of pts){const z=Math.hypot(p.x-q.x,p.y-q.y);if(z<105){c.strokeStyle=`rgba(190,220,185,${.14*(1-z/105)})`;c.beginPath();c.moveTo(p.x,p.y);c.lineTo(q.x,q.y);c.stroke()}}}requestAnimationFrame(draw)}resize();draw()}
  const grid=$('#repoGrid'),status=$('#repoStatus'),search=$('#repoSearch'),filters=$('#languageFilters');let repos=[],category='Web Apps';const fallback=[{name:'Joblifyr',description:'Responsive job-platform landing experience.',language:'PHP',html_url:'https://github.com/Jasfer2xp/Joblifyr'},{name:'Nova-Chain',description:'Interactive React and TypeScript web application.',language:'TypeScript',html_url:'https://github.com/Jasfer2xp/Nova-Chain'},{name:'Barangay',description:'Barangay information system desktop application.',language:'C#',html_url:'https://github.com/Jasfer2xp/Barangay'}];function escape(t=''){return t.replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]))}function typeOf(r){const n=(r.name+' '+(r.description||'')+' '+(r.language||'')).toLowerCase();if(/joblifyr|nova-chain|portfolio|website|mediconnect/.test(n))return'Web Apps';if(/barangay|c#|\.net|windows/.test(n))return'Desktop';if(/api|backend|server/.test(n))return'Backend';if(/database|mysql|sql|inventory/.test(n))return'Database';return'Other'}function render(){let list=repos.filter(r=>(category==='All'||typeOf(r)===category)&&(`${r.name} ${r.description||''}`.toLowerCase().includes(search.value.toLowerCase())));grid.innerHTML=list.length?list.map(r=>`<article class="repo-card"><h3>${escape(r.name)}</h3><p>${escape(r.description||'A public project from my development work.')}</p><footer><span>${typeOf(r)}</span><span>${r.language||'Code'}</span><a href="${r.html_url}" target="_blank" rel="noopener">View ↗</a></footer></article>`).join(''):'<p>No matching repositories found.</p>'}function makeFilters(){let types=['Web Apps','All','Desktop','Backend','Database','Other'];filters.innerHTML=types.map(t=>`<button class="${t===category?'active':''}" data-category="${t}">${t}</button>`).join('');$$('.filters button').forEach(b=>b.onclick=()=>{category=b.dataset.category;makeFilters();render()})}search.oninput=render;fetch('https://api.github.com/users/Jasfer2xp/repos?sort=updated&per_page=100').then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{repos=data.filter(r=>!r.fork);status.textContent=`${repos.length} public repositories · categorized by project type`;makeFilters();render()}).catch(()=>{repos=fallback;status.textContent='Selected public work · GitHub feed temporarily unavailable';makeFilters();render()});
})();
